
services:
 microservicio:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  environment:
   - spring.datasource.url=jdbc:oracle:thin:@bdexp1s1_tp?TNS_ADMIN=/ocmascotas/wallet
   - spring.datasource.username=DSY2201_S8_OCMascotas
   - spring.datasource.password=ActForm.S8_DSY
  restart: always